#!/bin/sh
#
# Gradle start up script for POSIX generated by the Gradle 'init' task
#
APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
APP_HOME=$(cd "$(dirname "$0")" && pwd)
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
exec java "-classpath" "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
